/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jebora_jebora_ImageEditing */

#ifndef _Included_com_jebora_jebora_ImageEditing
#define _Included_com_jebora_jebora_ImageEditing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jebora_jebora_ImageEditing
 * Method:    hello
 * Signature: ([IIIDI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jebora_jebora_ImageEditing_hello
  (JNIEnv *, jobject, jintArray, jint, jint, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
